/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconName } from "@fortawesome/fontawesome-svg-core";
export namespace Components {
    interface XButton {
        "allyLabel": string;
        "border": string;
        "color": 'primary' | 'secondary' | 'tertiary' | 'success' | 'error' | 'info' | 'warning';
        "disabled": boolean;
        "elevated": boolean;
        "height": string;
        "name": string;
        "rounded": boolean;
        "type": 'submit' | 'button';
        "value": string;
        "variant": 'solid' | 'outlined' | 'none';
        "width": string;
    }
    interface XCard {
        "variant": 'default' | 'champion';
    }
    interface XContainer {
        "background": string;
    }
    interface XDialog {
    }
    interface XIcon {
        "color": string;
        "name": IconName;
        "solid": boolean;
    }
    interface XPopover {
        "height": string;
        "open": boolean;
        "placement": 'top' | 'left' | 'bottom' | 'right';
        "width": string;
    }
    interface XTooltip {
        "height": string;
        "open": boolean;
        "placement": 'top' | 'left' | 'bottom' | 'right';
        "width": string;
    }
    interface XTypography {
    }
}
declare global {
    interface HTMLXButtonElement extends Components.XButton, HTMLStencilElement {
    }
    var HTMLXButtonElement: {
        prototype: HTMLXButtonElement;
        new (): HTMLXButtonElement;
    };
    interface HTMLXCardElement extends Components.XCard, HTMLStencilElement {
    }
    var HTMLXCardElement: {
        prototype: HTMLXCardElement;
        new (): HTMLXCardElement;
    };
    interface HTMLXContainerElement extends Components.XContainer, HTMLStencilElement {
    }
    var HTMLXContainerElement: {
        prototype: HTMLXContainerElement;
        new (): HTMLXContainerElement;
    };
    interface HTMLXDialogElement extends Components.XDialog, HTMLStencilElement {
    }
    var HTMLXDialogElement: {
        prototype: HTMLXDialogElement;
        new (): HTMLXDialogElement;
    };
    interface HTMLXIconElement extends Components.XIcon, HTMLStencilElement {
    }
    var HTMLXIconElement: {
        prototype: HTMLXIconElement;
        new (): HTMLXIconElement;
    };
    interface HTMLXPopoverElement extends Components.XPopover, HTMLStencilElement {
    }
    var HTMLXPopoverElement: {
        prototype: HTMLXPopoverElement;
        new (): HTMLXPopoverElement;
    };
    interface HTMLXTooltipElement extends Components.XTooltip, HTMLStencilElement {
    }
    var HTMLXTooltipElement: {
        prototype: HTMLXTooltipElement;
        new (): HTMLXTooltipElement;
    };
    interface HTMLXTypographyElement extends Components.XTypography, HTMLStencilElement {
    }
    var HTMLXTypographyElement: {
        prototype: HTMLXTypographyElement;
        new (): HTMLXTypographyElement;
    };
    interface HTMLElementTagNameMap {
        "x-button": HTMLXButtonElement;
        "x-card": HTMLXCardElement;
        "x-container": HTMLXContainerElement;
        "x-dialog": HTMLXDialogElement;
        "x-icon": HTMLXIconElement;
        "x-popover": HTMLXPopoverElement;
        "x-tooltip": HTMLXTooltipElement;
        "x-typography": HTMLXTypographyElement;
    }
}
declare namespace LocalJSX {
    interface XButton {
        "allyLabel"?: string;
        "border"?: string;
        "color"?: 'primary' | 'secondary' | 'tertiary' | 'success' | 'error' | 'info' | 'warning';
        "disabled"?: boolean;
        "elevated"?: boolean;
        "height"?: string;
        "name"?: string;
        "rounded"?: boolean;
        "type"?: 'submit' | 'button';
        "value"?: string;
        "variant"?: 'solid' | 'outlined' | 'none';
        "width"?: string;
    }
    interface XCard {
        "variant"?: 'default' | 'champion';
    }
    interface XContainer {
        "background"?: string;
    }
    interface XDialog {
    }
    interface XIcon {
        "color"?: string;
        "name"?: IconName;
        "solid"?: boolean;
    }
    interface XPopover {
        "height"?: string;
        "open"?: boolean;
        "placement"?: 'top' | 'left' | 'bottom' | 'right';
        "width"?: string;
    }
    interface XTooltip {
        "height"?: string;
        "open"?: boolean;
        "placement"?: 'top' | 'left' | 'bottom' | 'right';
        "width"?: string;
    }
    interface XTypography {
    }
    interface IntrinsicElements {
        "x-button": XButton;
        "x-card": XCard;
        "x-container": XContainer;
        "x-dialog": XDialog;
        "x-icon": XIcon;
        "x-popover": XPopover;
        "x-tooltip": XTooltip;
        "x-typography": XTypography;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "x-button": LocalJSX.XButton & JSXBase.HTMLAttributes<HTMLXButtonElement>;
            "x-card": LocalJSX.XCard & JSXBase.HTMLAttributes<HTMLXCardElement>;
            "x-container": LocalJSX.XContainer & JSXBase.HTMLAttributes<HTMLXContainerElement>;
            "x-dialog": LocalJSX.XDialog & JSXBase.HTMLAttributes<HTMLXDialogElement>;
            "x-icon": LocalJSX.XIcon & JSXBase.HTMLAttributes<HTMLXIconElement>;
            "x-popover": LocalJSX.XPopover & JSXBase.HTMLAttributes<HTMLXPopoverElement>;
            "x-tooltip": LocalJSX.XTooltip & JSXBase.HTMLAttributes<HTMLXTooltipElement>;
            "x-typography": LocalJSX.XTypography & JSXBase.HTMLAttributes<HTMLXTypographyElement>;
        }
    }
}
