/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XContainer {
        "background": string;
    }
    interface XDialog {
    }
    interface XPopover {
    }
}
declare global {
    interface HTMLXContainerElement extends Components.XContainer, HTMLStencilElement {
    }
    var HTMLXContainerElement: {
        prototype: HTMLXContainerElement;
        new (): HTMLXContainerElement;
    };
    interface HTMLXDialogElement extends Components.XDialog, HTMLStencilElement {
    }
    var HTMLXDialogElement: {
        prototype: HTMLXDialogElement;
        new (): HTMLXDialogElement;
    };
    interface HTMLXPopoverElement extends Components.XPopover, HTMLStencilElement {
    }
    var HTMLXPopoverElement: {
        prototype: HTMLXPopoverElement;
        new (): HTMLXPopoverElement;
    };
    interface HTMLElementTagNameMap {
        "x-container": HTMLXContainerElement;
        "x-dialog": HTMLXDialogElement;
        "x-popover": HTMLXPopoverElement;
    }
}
declare namespace LocalJSX {
    interface XContainer {
        "background"?: string;
    }
    interface XDialog {
    }
    interface XPopover {
    }
    interface IntrinsicElements {
        "x-container": XContainer;
        "x-dialog": XDialog;
        "x-popover": XPopover;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "x-container": LocalJSX.XContainer & JSXBase.HTMLAttributes<HTMLXContainerElement>;
            "x-dialog": LocalJSX.XDialog & JSXBase.HTMLAttributes<HTMLXDialogElement>;
            "x-popover": LocalJSX.XPopover & JSXBase.HTMLAttributes<HTMLXPopoverElement>;
        }
    }
}
